# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gcg = {
    pname = "gcg";
    version = "v360";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "gcg";
      rev = "v360";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-MRgsmP9LuTpS/FEPBNJSrIbYlUGh8EOEcbbl0MVEiRA=";
    };
  };
  ipopt = {
    pname = "ipopt";
    version = "releases/3.14.16";
    src = fetchFromGitHub {
      owner = "coin-or";
      repo = "Ipopt";
      rev = "releases/3.14.16";
      fetchSubmodules = false;
      sha256 = "sha256-ZuiZZMq7NzOm6CCJgMBgEWs8PEfM3pVr2yOWbS42l8U=";
    };
  };
  mip-dd = {
    pname = "mip-dd";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "MIP-DD";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-1xUBhBq0Ie4MG65GW4UrWKcRj1Po/uT7Z1tptu7DTL0=";
    };
  };
  mumps-harness = {
    pname = "mumps-harness";
    version = "releases/3.0.7";
    src = fetchFromGitHub {
      owner = "coin-or-tools";
      repo = "ThirdParty-Mumps";
      rev = "releases/3.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-4P/aR2oUKU5l3eTVs8twQHS3fyPDD7rkAcFc20ZzZHU=";
    };
  };
  papilo = {
    pname = "papilo";
    version = "v2.2.1";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "papilo";
      rev = "v2.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-NMzFXyrmewnPLodohBE0AMhjSln7yEJcnIxxhDjfT0U=";
    };
  };
  pygcgopt = {
    pname = "pygcgopt";
    version = "6e2e51aabd11d3cb4ebdf79992c3618758801016";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PyGCGOpt";
      rev = "6e2e51aabd11d3cb4ebdf79992c3618758801016";
      fetchSubmodules = false;
      sha256 = "sha256-1nf5ctEBDR9ZFEOPcHFa+9qnytWkiydZaP8RZhG2XXY=";
    };
    date = "2024-03-08";
  };
  pyscipopt = {
    pname = "pyscipopt";
    version = "v5.0.1";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PySCIPOpt";
      rev = "v5.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-zfebn7jhvDndWAn+eB0q+2iOjPIqY143bbaKePl4FSQ=";
    };
  };
  pysoplex = {
    pname = "pysoplex";
    version = "0def0a370ea08d1f1f34b0e5a2e03f7e5881ac9c";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PySoPlex";
      rev = "0def0a370ea08d1f1f34b0e5a2e03f7e5881ac9c";
      fetchSubmodules = false;
      sha256 = "sha256-8/bndwQ0aUSMl3XTZctfW3SH85IIrlCln6+9cQGuU9Q=";
    };
    date = "2024-02-27";
  };
  scip = {
    pname = "scip";
    version = "v901";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "scip";
      rev = "v901";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-WCudyGop5QQZaMQpKHGFQg1fUXHQRohxRlEpsmMVrDY=";
    };
  };
  scippp = {
    pname = "scippp";
    version = "1.2.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "SCIPpp";
      rev = "1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-RbxIgATECLJCopShm98+ogfFoCv2yWH1/1QcZyo9GKo=";
    };
  };
  soplex = {
    pname = "soplex";
    version = "release-701";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "soplex";
      rev = "release-701";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-n8NfMXr6ALFQEgVLk9Nxx724tqFAk17bMZ6YgjUagg8=";
    };
  };
  vipr = {
    pname = "vipr";
    version = "65fda95f4412c1395bfd65ce706f84103d4afe54";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "vipr";
      rev = "65fda95f4412c1395bfd65ce706f84103d4afe54";
      fetchSubmodules = false;
      sha256 = "sha256-glbEBfj17bolh9YrjrAkWRo5JMJbu7ph5R+oRDzjdgA=";
    };
    date = "2024-05-07";
  };
}
